controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
admin_dashboard:
    path: /admin/dashboard
    controller: EasyCorp\Bundle\EasyAdminBundle\Controller\AdminDashboardController::index