# config/packages/easy_admin.yaml
easy_admin:
  entities:
    User:
      class: App\Entity\User
    AdminUser:
      class: App\Entity\AdminUser
  design:
    menu:
      - { entity: 'User', label: 'Users' }
      - { entity: 'AdminUser', label: 'Admin Users' }
    Movie:
      class: App\Entity\Movie
      form:
        fields:
          - 'title'
          - 'description'
          - 'releasedate'
          - 'image'
          - 'budget'
          - { property: 'category', type: 'entity', type_options: { class: 'App\Entity\Category' } }
